<?php
$netflix = array(
    array('id' => 1, 'nome'=> "Guerra Infinita", 'foto' => "./imagens/poster-guerra-infinita.png", 'data' => "2018-04-26", 'Genero' => "Açao, Ficção Cientifica, Super-Herói, Aventura e Fantasia", 'Diretores' => "Anthony Russo e Joe Russo", 'Roteiristas' => "Stephen McFeely e Christopher Markus", 'Bilheteria' => "US$ 2,052 bilhões", 'Orcamento' => "US$ 316 milhões"),
    array('id' => 2, 'nome'=> "O Poderoso Chefão", 'foto' => "./imagens/poster-poderoso-chefao.png", 'data' => "1972-03-24", 'Genero' => "Mafia, Drama e Policial", 'Diretores' => "Fancis Ford Coppola", 'Roteiristas' => "Fancis Ford Coppola e Mario Puzo", 'Bilheteria' => "US$ 120 milhoes", 'Orcamento' => "US$ 2 milhões"),
    array('id' => 3, 'nome'=> "Parasita", 'foto' => "./imagens/poster-parasita.png", 'data' => "2019-11-07", 'Genero' => "Suspense", 'Diretores' => "Joon-ho Bong", 'Roteiristas' => "Joon-ho Bong e Jin Won Han", 'Bilheteria' => "US$ 204 milhoes", 'Orcamento' => "US$ 11 milhões"),
    array('id' => 4, 'nome'=> "1917", 'foto' => "./imagens/poster-1917.png", 'data' => "2020-01-23", 'Genero' => "Guerra", 'Diretores' => "Sam Mendes", 'Roteiristas' => "Sam Mendes e Krysty Wilson-Cairns", 'Bilheteria' => "US$ 384,6 milhoes", 'Orcamento' => "US$ 100 milhões"),
    array('id' => 5, 'nome'=> "O Irlandês", 'foto' => "./imagens/poster-o-irlandes.png", 'data' => "2020-07-08", 'Genero' => "Suspense e Biográfico", 'Diretores' => "Martin Scorcese", 'Roteiristas' => "Steve Zaillian", 'Bilheteria' => "Não teve exibição cinematográfrica", 'Orcamento' => "US$ 160 milhões"),
    array('id' => 6, 'nome'=> "Auto da Compadecida", 'foto' => "./imagens/poster-auto-da-compadecida.png", 'data' => "2000-09-10", 'Genero' => "Comédia e Aventura", 'Diretores' => "Guel Arraes", 'Roteiristas' => "Guel Arraes e João Falcão", 'Bilheteria' => "R$ 11,4 milhões", 'Orcamento' => "R$ 400 mil"),
    array('id' => 7, 'nome'=> "John Wick: De volta ao Jogo", 'foto' => "./imagens/poster-de-volta-ao-jogo.png", 'data' => "2014-11-27", 'Genero' => "Ação", 'Diretores' => "David Leitch, Chad Stahelski", 'Roteiristas' => "Derek Kolstad", 'Bilheteria' => "US$ 86,1 milhões", 'Orcamento' => "US$ 20 milhões"),
    array('id' => 8, 'nome'=> "O Pianista", 'foto' => "./imagens/poster-o-pianista.png", 'data' => "2003-03-07", 'Genero' => "Drama e Histórico", 'Diretores' => "Roman Polanski", 'Roteiristas' => "Roman Polanski e Ronald Harwood", 'Bilheteria' => "US$ 120 milhões", 'Orcamento' => "US$ 35 milhões"),
    array('id' => 9, 'nome'=> "O Grande Ditador", 'foto' => "./imagens/poster-o-grande-ditador.png", 'data' => "1942-08-12", 'Genero' => "Comédia e Sátira", 'Diretores' => "Charles Chaplin", 'Roteiristas' => "Charles Chaplin", 'Bilheteria' => "US$ 5 milhões", 'Orcamento' => "US$ 2 milhões"),
    array('id' => 10, 'nome'=> "A Grande Aposta", 'foto' => "./imagens/poster-a-grande-aposta.png", 'data' => "2016-01-14", 'Genero' => "Drama, Comédia e Biografia", 'Diretores' => "Adam Mckay", 'Roteiristas' => "Adam Mckay e Charles Randolph", 'Bilheteria' => "US$ 28 milhões", 'Orcamento' => "US$ 133,4 milhões"),
    array('id' => 11, 'nome'=> "O Destino de uma Nação", 'foto' => "./imagens/poster-o-destino-de-uma-nação.png", 'data' => "2018-01-11", 'Genero' => "Histórico", 'Diretores' => "Joe Wright", 'Roteiristas' => "Anthony McCarten", 'Bilheteria' => "US$ 150 milhões", 'Orcamento' => "US$ 30 milhões"),
    array('id' => 12, 'nome'=> "Rocketmam", 'foto' => "./imagens/poster-rocketman.png", 'data' => "2019-05-30", 'Genero' => "Biografico e Musical", 'Diretores' => "Dexter Fletcher", 'Roteiristas' => "Lee Hall", 'Bilheteria' => "US$ 192,2 milhões", 'Orcamento' => "US$ 40 milhões"),
    array('id' => 13, 'nome'=> "Bohemia Rhapsody", 'foto' => "./imagens/poster-bohemiam-rhapsody.png", 'data' => "2018-11-01", 'Genero' => "Biografico e Musical", 'Diretores' => "Bryan Singer", 'Roteiristas' => "Anthony McCarten", 'Bilheteria' => "US$ 910 milhões", 'Orcamento' => "US$ 52 milhões"),
    array('id' => 14, 'nome'=> "Coringa", 'foto' => "./imagens/poster-coringa.png", 'data' => "2019-10-03", 'Genero' => "Drama", 'Diretores' => "Todd Phillips", 'Roteiristas' => "Todd Phillips e Scott Silver", 'Bilheteria' => "US$ 1 bilhão", 'Orcamento' => "US$ 55 milhôes"),
    array('id' => 15, 'nome'=> "Star Wars: O Império Contra Ataca", 'foto' => "./imagens/poster-star-wars-o-império-contra-ataca.png", 'data' => "1980-07-21", 'Genero' => "Ficção Científica", 'Diretores' => "irvin Keshner", 'Roteiristas' => "Lawrence Kasdan e George Lucas", 'Bilheteria' => "US$ 547 milhões", 'Orcamento' => "US$ 23 milhões"),
);
?>                 